project_id = "upmiqdnbvojpodgucxmw"

[functions.send-contact-email]
verify_jwt = false

[functions.send-download-confirmation]
verify_jwt = false

[functions.zapier-blog-webhook]
verify_jwt = false

[functions.chat]
verify_jwt = false
